### ISSUE TITLE
Feature request: When pressing enter in the activity inputs, create a new line

### ISSUE THREAD

**Issue by amenk** [Derkyela/pert-calculator#12]
Use case: Create new items quickly by pressing enter in any of the input fields.

**Comment by Derkyela** [comment]
@amenk great idea! I have just implemented it. When pressing `enter` within an activity, you will add a new one which will be focus. This way you can seamlessly continue adding activities without having to tab to the add button.

**Comment by amenk** [comment]
Thank you
