### ISSUE TITLE
Add warning "!!!" to table output

### ISSUE THREAD

**Issue by amenk** [Derkyela/pert-calculator#3]
I like to copy the HTML output to our ticket system.

But now you don't see the STANDARD DEVIATION OF TIME warning because the color code is not copied - what do you think about adding a !!! to add?

Also this would improve accessibility (color blindness).

**Comment by Derkyela** [comment]
I think adding a ! is a good idea.

**Comment by Derkyela** [comment]
I added a ! prefix to the marked values. As well as emphasizing them via `<strong>`.

**Comment by amenk** [comment]
thanks
