### ISSUE TITLE
Idea: Import activities from HTML table

### ISSUE THREAD

**Issue by amenk** [Derkyela/pert-calculator#4]
Might be to complicated, but what do you think about importing from the actual HTML output so there is no need for a .json file to pass around?

**Comment by Derkyela** [comment]
That's an interesting idea. I think it should be either copied with the table header so that a assignment to the right properties is possible or alternatives with a fixed order of properties.

**Comment by amenk** [comment]
yes, I think it makes sense to add a copy-to-clipboard button to ensure the right HTML Is copied.

**Comment by Derkyela** [comment]
@amenk I just merged the first implementation of this feature. It is now possible to import activities from a html table. I have also added a copy button for convenience.

Import via html list or plain text will be added in future.

**Comment by Derkyela** [comment]
HTML list support is added in #8.

**Comment by amenk** [comment]
Std Dev of Time does not always recalculate. 
1. copy result table
2. paste to EasyRedmine
3. copy from EasyRedmin
4. all but the standard deviation of time is imported, standard devitation of time displays "NaN"

**Comment by DanieliMi** [comment]
Problem is the ! if the standard deviation of is is imported. Example:
Activity Title | Optimistic Time | Most Likely Time | Pessimistic Time | Expected Time | Standard Deviation of Time
-- | -- | -- | -- | -- | --
asd | 1 | 2 | 3 | 2 | 0.33
asdasd | 1 | 4 | 44 | 10.17 | 7.17 !
